services:
  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_POCKETBASE_URL=${REACT_APP_POCKETBASE_URL:-https://pocketbase.tenderfuchs.de}
        - REACT_APP_OPENAI_API_KEY=${REACT_APP_OPENAI_API_KEY}
        - REACT_APP_LLM_MODEL=${REACT_APP_LLM_MODEL:-gpt-3.5-turbo}
        - REACT_APP_LLM_API_URL=${REACT_APP_LLM_API_URL}
    container_name: tenderfuchs-dashboard
    restart: unless-stopped
    ports:
      - "80:80"